### ISSUE TITLE
sketching & design home page 

### ISSUE THREAD

**Issue by maqalaqil** [ReCoded-Org/capstone-project-rescrap#1]
# 
Assigned to: @ArhabAlShargabi 
Created At: 10-10-2020
Started At: --
Ended At: --
Expected Duration: 1.5 (tomorrow 6pm)

## Tasks
- [x] nav bar 

- [x] slider or anything in mind

- [x] how it works section

- [x] number bar to show statistics

- [x] list of products

- [x] footer
