### ISSUE TITLE
Configure React Router

### ISSUE THREAD

**Issue by Ahmed-aleryani** [ReCoded-Org/capstone-project-rescrap#39]
# 
Assigned to: @Ahmed-aleryani 
Created At: 10:00 AM 29/10/2020
Started At: 11:05 AM 29/10/2020
Ended At: 11:50 AM 29/10/2020
Expected Duration: 1~2 Hours

## Tasks
- [x] Add react router DOM.

- [x] Configure the Nav links.

- [x] Prepare Switch that will change the components dynamically according to link.
