### ISSUE TITLE
Build Home page

### ISSUE THREAD

**Issue by Ahmed-aleryani** [ReCoded-Org/capstone-project-rescrap#42]
# 
Assigned to: @Tahany-Alswoidy & @NusibaIbrahim 
Created At: 4:40 PM 29/10/2020
Started At: 10:15 PM 29/10/2020
Ended At:   9:00  PM 4/11/2020   
Expected Duration: 4

## Tasks
- [x] Build Intro section (section 1 - Tahany).

- [x] Build Sellers section (section 2 - Tahany).

- [x] Build Buyers section (section 3 - Tahany).

- [x] Build New Offers section (section 4 - Nusiba).

- [x] Build Last section before footer (section 5 - Nusiba).

### The following tasks you should discuss among you and decide who will do them

- [x] Build Home.jsx file and import the elements into the container. 

- [x] Build tests for Tahany's components.

- [x] Build tests for Nisba's components.

- [x] Build Test for Home page as follows Home.test.js

Note*: you will create a branch for this issue and end it with your name for example(Home-Tahany) for Tahany and (Home-Nusiba) for Nusiba. You will only stage the changes you made only, don't use (git add . ) this method causes issues and conflicts.
