### ISSUE TITLE
Build About us page

### ISSUE THREAD

**Issue by Ahmed-aleryani** [ReCoded-Org/capstone-project-rescrap#43]
# 
Assigned to: @ArhabAlShargabi 
Created At: 4:55 PM 29/10/2020
Started At: 31/10/2020
Ended At: 2/11/2020
Expected Duration: 3

## Tasks
- [x] Build About us sub-sections.

- [x] Combine Sub-sections and add them to About-us.jsx

- [x] Build Test for your components.

- [x] Apply necessary styles.

- [x] Your work is in folder named with About-us which is inside containers folder.

Note*: you will create a branch for this issue and end it with your name for example in your case(about-us-arhab). Also You will only stage the changes you made only, don't use (git add . ) this method causes issues and conflicts.
