### ISSUE TITLE
Build contact us page

### ISSUE THREAD

**Issue by Ahmed-aleryani** [ReCoded-Org/capstone-project-rescrap#44]
# 
Assigned to: @Hanan712 
Created At: 9:26 PM 29/10/2020
Started At: --
Ended At: --
Expected Duration: 

## Tasks
- [ ] Create branch for the issue e.g(contact-us-hanan)

- [ ] Create Filter section component.

- [ ] Build form component.

- [ ] Build side section that contains title and description component.

- [ ] Build ContactUs.jsx container and import the built components.

Note*: You will only stage the changes you made only, don't use (git add . ) this method causes issues and conflicts.
