### ISSUE TITLE
Build product details page

### ISSUE THREAD

**Issue by Ahmed-aleryani** [ReCoded-Org/capstone-project-rescrap#45]
# 
Assigned to: @malthawr 
Created At: 10:19 PM 29/10/2020
Started At: 11:46 AM 2/11/2020
Ended At: 10:42 PM 5/11/2020
Expected Duration: 4 days

## Tasks
- [x] Build component for the first section of product details which contains an image, title, description and price of product.

- [x] Build details and sellers component section.

- [x] Build Other offers card slider component.

- [x] Import components into ProductDetails.jsx container.

Note*: You will only stage the changes you made only, don't use (git add . ) this method causes issues and conflicts.
