### ISSUE TITLE
Prepare Authentication with google using firebase 

### ISSUE THREAD

**Issue by Ahmed-aleryani** [ReCoded-Org/capstone-project-rescrap#48]
# Prepare Authentication with google using firebase
Assigned to: @Ahmed-aleryani 
Created At: 10:15 PM 31/10/2020
Started At: 11:00 PM 31/10/2020
Ended At: --
Expected Duration: 

## Tasks
- [x] Configure google signin.

- [x] If first time login, show form to request from user to add additional details.

- [x] Prepare state to store login session.
